name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - uses: yezz123/setup-uv@v4
        with:
          uv-version: "0.2.33"
          uv-venv: .venv

      - uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: python-${{ runner.os }}-hashFiles("pyproject.toml")-3.12.4-uv

      - name: Install dependencies
        run: uv pip install . --requirement pyproject.toml --all-extras --no-cache
  pre-commit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - uses: yezz123/setup-uv@v4
        with:
          uv-version: "0.2.33"
          uv-venv: .venv

      - uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: python-${{ runner.os }}-hashFiles("pyproject.toml")-3.12.4-uv

      - name: Install dependencies
        run: uv pip install . --requirement pyproject.toml --all-extras --no-cache

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all-files
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - uses: yezz123/setup-uv@v4
        with:
          uv-version: "0.2.33"
          uv-venv: .venv

      - uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: python-${{ runner.os }}-hashFiles("pyproject.toml")-3.12.4-uv

      - name: Install dependencies
        run: uv pip install -e . --requirement pyproject.toml --all-extras --no-cache

      - name: Run tests
        run: pytest --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
