"""initial migration

Revision ID: 7a99988058f2
Revises:
Create Date: 2024-08-05 23:43:13.660638

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from telegram_bot_template.infrastructure.db.models.user import USER_ROLE_ENUM

# revision identifiers, used by Alembic.
revision: str = "7a99988058f2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    USER_ROLE_ENUM.create(op.get_bind())  # type: ignore[no-untyped-call]
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("role", USER_ROLE_ENUM, nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("telegram_id", name="uq_user_telegram_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    USER_ROLE_ENUM.drop(op.get_bind())  # type: ignore[no-untyped-call]
    # ### end Alembic commands ###
